### ISSUE TITLE
Error: Mutations fields must be an object with field names as keys or a function which returns such an object.

### ISSUE THREAD

**Issue by morenoh149** [Glavin001/graphql-sequelize-crud#21]
Not sure if I should ask here or upstream. I'm trying to run this tool on an existing api running sequelize.

```
$ node index.js
{"name":"foo","version":"0.0.1","event":"state","state":"booting"}
/Users/harrymoreno/programming/foo/node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
    ^

Error: Mutations fields must be an object with field names as keys or a function which returns such an object.
    at invariant (/Users/harrymoreno/programming/foo/node_modules/graphql/jsutils/invariant.js:19:11)
    at defineFieldMap (/Users/harrymoreno/programming/foo/node_modules/graphql/type/definition.js:324:27)
    at GraphQLObjectType.getFields (/Users/harrymoreno/programming/foo/node_modules/graphql/type/definition.js:285:44)
    at /Users/harrymoreno/programming/foo/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/Users/harrymoreno/programming/foo/node_modules/graphql/type/schema.js:219:7)
    at Array.reduce (native)
    at new GraphQLSchema (/Users/harrymoreno/programming/foo/node_modules/graphql/type/schema.js:95:34)
    at getSchema (/Users/harrymoreno/programming/foo/node_modules/graphql-sequelize-crud/lib/index.js:887:10)
```
Is my data model not compatible with graphql?

**Comment by Glavin001** [comment]
Please provide a sample code snippet which can be used to reproduce this error.
